### ISSUE TITLE
Blue links not clickable?

### ISSUE THREAD

**Issue by Jolg42** [optoolco/beta#12]
I am not sure they are links because clicking on them doesn't work.

I expected to get somewhere or this to open a webpage in my browser.
<img width="809" alt="Screen Shot 2021-01-11 at 18 15 02" src="https://user-images.githubusercontent.com/1328733/104215448-0cd3ac80-5439-11eb-966a-de95610fcd44.png">
<img width="793" alt="Screen Shot 2021-01-11 at 18 14 14" src="https://user-images.githubusercontent.com/1328733/104215449-0e9d7000-5439-11eb-8bf0-f717d281714f.png">
<img width="806" alt="Screen Shot 2021-01-11 at 18 14 10" src="https://user-images.githubusercontent.com/1328733/104215453-0f360680-5439-11eb-97d4-d2b4ef9c0f01.png">

**Comment by heapwolf** [comment]
Fixed. Will add to next release.

**Comment by heapwolf** [comment]
Verified to be fixed.
