### ISSUE TITLE
Functions: project local path placeholder

### ISSUE THREAD

**Issue by juliangruber** [optoolco/beta#14]
![image](https://user-images.githubusercontent.com/10247/104308751-71424a80-54d1-11eb-9981-752c46d42275.png)

This is not where I put it

**Comment by Raynos** [comment]
A newly created project does not show the local code directory that the user choose.

**Comment by heapwolf** [comment]
yeah, the placeholder text is an example of where you might put it. Isn't that pretty typical? The git remote also is not your remote.

**Comment by juliangruber** [comment]
This is the project overview screen, and below the title it shows a "Local" path, right after I had to choose a local path when creating the project. So there is a local path already, why not show it here? And the Git stuff is below the form fields, so I didn't think these form fields would be about git.

**Comment by Raynos** [comment]
Yeah, it's a bug that we dont show the local path you choose for the boilerplate directory.

**Comment by heapwolf** [comment]
@Raynos yeah confirmed, looks like the value isn't being captured for some reason on windows.

**Comment by Raynos** [comment]
A fix was released yesterday for this.
