### ISSUE TITLE
Functions: How to create function?

### ISSUE THREAD

**Issue by juliangruber** [optoolco/beta#15]
In this screen, how do I create a new function?

![image](https://user-images.githubusercontent.com/10247/104308852-90d97300-54d1-11eb-8adf-efbb334b56e5.png)

**Comment by Raynos** [comment]
You can create a function by adding local code directory and choosing a file.

Once you've chosen a file e.g. `index.js` , you can then deploy that file as a function.

**Comment by heapwolf** [comment]
There could be some copy on this screen that says `To get started, select a local directory for your project's code.`

**Comment by juliangruber** [comment]
As mentioned in the other issue, I have selected a local directory already. So next I should create a file in there and then try again?

Since I used a noidejs boilerplate, I expected for the basic structure to be created by Functions

**Comment by heapwolf** [comment]
This confusion is being caused by the same issue in #14, the value of the selected directory is not being captured on Windows. Solving #14 will fix this issue.
