### ISSUE TITLE
Functions: Git integration doesn't turn on

### ISSUE THREAD

**Issue by juliangruber** [optoolco/beta#22]
![image](https://user-images.githubusercontent.com/10247/104309288-32f95b00-54d2-11eb-8fd3-42b6152670ca.png)

**Comment by Raynos** [comment]
The git integration toggle might not work if the local code directory is empty

**Comment by heapwolf** [comment]
Git integration is not possible unless you have chosen a directory, we could hide it until the user selects one.

**Comment by juliangruber** [comment]
I was prompted to chose a directory while creating the project, and I selected one

**Comment by heapwolf** [comment]
I see that the directory is not populating with the value of the directory selected. I can't reproduce on mac or linux.
