### ISSUE TITLE
Functions: Save file doesn't do anything

### ISSUE THREAD

**Issue by juliangruber** [optoolco/beta#23]
![image](https://user-images.githubusercontent.com/10247/104309354-502e2980-54d2-11eb-8889-701db5a5acc5.png)

**Comment by Raynos** [comment]
The save file menu item will only save the currently selected file. You currently have zero files in your project.

**Comment by heapwolf** [comment]
We could remove this possibly and only have the inline save when it becomes relevant.

**Comment by juliangruber** [comment]
What about disabling the label when no file is selected?
