### ISSUE TITLE
Operator: Error on 2nd launch

### ISSUE THREAD

**Issue by juliangruber** [optoolco/beta#25]
I got this in the error dialog. The submit button is spinning, not sure if it was submitted.

### STACK

```
Error: Uncaught Error: Error invoking remote method 'api': Error: IPC api feedback:postFeedback has uncaught: arg.license required
```

### SYSTEM SUMMARY

```
Operator v0.1.18
Windows_NT x64 10.0.19041

Wizards: v0.1.18
Buckets: v0.1.10
Functions: v0.1.5
Data: v0.1.4
Electron: v11.1.1
```

**Comment by juliangruber** [comment]
This happens when I launch the Data app. Now it's downloading it again, although I had already run it before.

**Comment by Raynos** [comment]
It’s downloading it again because we released an update and it’s downloading the update.

**Comment by Raynos** [comment]
In fact I fixed arg.license today, since you’ve downloaded the update you shouldn’t see this error again.
