### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by pfrazee** [optoolco/beta#3]
Hey yall, got the invite, happy to give Optools a look!

I followed the download link and the CTA on the page is to subscribe to the newsletter. Is that right?

![image](https://user-images.githubusercontent.com/1270099/104212383-cbbca780-53fa-11eb-8706-3e1c5ba6fc99.png)

**Comment by Raynos** [comment]
We ask you to enter your email before you can download our app.

Unfortunately our website doesnt know you are already subscribed, if you enter your email you can download the software.

We will try a fix for this.

**Comment by pfrazee** [comment]
Cool no worries. If this is common for the flow, just some copy explaining where I'm headed would help

**Comment by heapwolf** [comment]
Fixed. Thanks @pfrazee :)
