### ISSUE TITLE
Cannot `Launch Data`

### ISSUE THREAD

**Issue by Jolg42** [optoolco/beta#5]
<img width="893" alt="Screen Shot 2021-01-11 at 18 02 18" src="https://user-images.githubusercontent.com/1328733/104214149-63d88200-5437-11eb-9dd8-5ca541fce227.png">

### STACK

```
Error: Uncaught Error: Error invoking remote method 'api': Error: IPC api launcher:launch has uncaught: Command failed: cp -R /Applications/Operator.app/Contents/Resources/apps/Data.app /Applications/Data.app
cp: /Applications/Operator.app/Contents/Resources/apps/Data.app: No such file or directory

```

### SYSTEM SUMMARY

```
Operator v0.1.17
Darwin x64 19.6.0

Wizards: v0.1.17
Buckets: v0.1.9
Functions: v0.1.5
Data: v0.1.4
Electron: v11.1.1
```

**Comment by Raynos** [comment]
I see that we don't have `Applications/Operator.app/Contents/Resources/apps/Data.app` in our repo.

**Comment by Jolg42** [comment]
This probably helps https://github.com/optoolco/beta/issues/7#issuecomment-758115589

**Comment by heapwolf** [comment]
Verified to be fixed.
