### ISSUE TITLE
`Functions` is loading indefinitely

### ISSUE THREAD

**Issue by Jolg42** [optoolco/beta#6]
<img width="1341" alt="Screen Shot 2021-01-11 at 17 59 32" src="https://user-images.githubusercontent.com/1328733/104214377-a26e3c80-5437-11eb-9214-af313e8eb0c6.png">

```
Operator v0.1.17
Darwin x64 19.6.0

Wizards: v0.1.17
Buckets: v0.1.9
Functions: v0.1.5
Data: v0.1.4
Electron: v11.1.1
```

**Comment by Raynos** [comment]
The `functions` app has a logfile that get's written to if something goes wrong which could load to an indefinite spinner.

[Our FAQ has a section about finding logfiles](https://optool.co/docs/?faq/can-i-share-the-logs-for-the-operator-application-)

If your on mac it should be `~/Library/Application Support/Functions/optoolco/logs.nldj` , if you could share that log file with any errors that would help us track down where the loading got stuck.

**Comment by Jolg42** [comment]
See https://github.com/optoolco/beta/issues/7#issuecomment-758115589

**Comment by Jolg42** [comment]
Looks like it loads with the latest version

Functions v0.1.18
Darwin x64 19.6.0

Wizards: v0.1.18
Buckets: NA
Functions: v0.1.5
Data: NA
Electron: v11.1.1
