### ISSUE TITLE
`Error Access Denied` for `Deploy a Website`

### ISSUE THREAD

**Issue by Jolg42** [optoolco/beta#8]
<img width="894" alt="Screen Shot 2021-01-11 at 18 01 53" src="https://user-images.githubusercontent.com/1328733/104214566-e103f700-5437-11eb-9fcd-fe822262cef1.png">

This doesn't say why, more information here would help.

```
Operator v0.1.17
Darwin x64 19.6.0

Wizards: v0.1.17
Buckets: v0.1.9
Functions: v0.1.5
Data: v0.1.4
Electron: v11.1.1
```

**Comment by Raynos** [comment]
The `Access Denied` error comes from the `aws-sdk` , we need to surface more error and see if we can handle this more gracefully.

Deploy website attempts to list the S3 buckets in your account and it appears your credentials do not have S3 access for at least one of the profiles in your `~/.aws/credentials` file.

**Comment by Jolg42** [comment]
That makes sense. Though I have 2 different AWS profiles locally so I don't know from which one it is (I guess default). And I cannot choose the other one in the UI?

**Comment by heapwolf** [comment]
We've just been editing the `~/.aws/credentials` file, but that would be great.

**Comment by Raynos** [comment]
You can view the two AWS profiles in Operator application under `Settings` => `AWS Profiles` ; they are both selected and read by default.

**Comment by Jolg42** [comment]
I see them both in the `AWS Profiles` section but I guess you select one by default for some areas of the app?

**Comment by Raynos** [comment]
The `deploy website` wizard will search for S3 buckets in all profiles ( both of them ). All of the applications are multi profile so you don't have to switch

**Comment by Raynos** [comment]
We released a new version of the application that shows improved messages around AWS permission issues.
